/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.skife.waffles;

import org.apache.maven.artifact.Artifact;
import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.project.MavenProject;
import org.apache.maven.project.MavenProjectHelper;
import org.apache.maven.project.artifact.AttachedArtifact;
import org.codehaus.plexus.util.FileUtils;
import org.codehaus.plexus.util.IOUtil;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.net.URLClassLoader;
import java.util.ArrayList;
import java.util.List;

/**
 * Make an artifact generated by the build really executable. The resulting artifact
 * can be run directly from the command line (Java must be installed and in the
 * shell path).
 *
 * @goal really-executable-jar
 */
public class MyMojo extends AbstractMojo
{
    /**
     * The Maven project.
     *
     * @parameter expression="${project}"
     * @required
     * @readonly
     */
    private MavenProject project;

    /**
     * @component
     * @required
     * @readonly
     */
    private MavenProjectHelper projectHelper;

    /**
     * Java command line arguments to embed. Only used with the default stanza.
     *
     * @parameter
     */
    private String flags = "";

    /**
     * Name of the generated binary.
     *
     * @parameter
     */
    private String programFile = null;

    /**
     * Specifies the classifier of the artifact that will be made executable.
     *
     * @parameter
     */
    private String classifier;

    /**
     * Attach the binary as an artifact to the deploy.
     *
     * @parameter
     */
    private boolean attachProgramFile = false;

    /**
     * File ending of the program artifact.
     *
     * @parameter
     */
    private String programFileType = "sh";

    /**
     * Shell script to add to the jar instead of the default stanza.
     *
     * @parameter
     * @throws MojoExecutionException
     */
    private String scriptFile = null;

    public void execute() throws MojoExecutionException
    {
        try {
            List<File> files = new ArrayList<File>();

            if (shouldProcess(project.getArtifact())) {
                files.add(project.getArtifact().getFile());
            }

            for (Object item : project.getAttachedArtifacts()) {
                AttachedArtifact artifact = (AttachedArtifact) item;
                if (shouldProcess(artifact)) {
                    files.add(artifact.getFile());
                }
            }

            if (files.isEmpty()) {
                throw new MojoExecutionException("Could not find any jars to make executable");
            }

            if (programFile != null && !programFile.matches("\\s+")) {
                for (File file : files) {
                    File dir = file.getParentFile();
                    File exec = new File(dir, programFile);
                    FileUtils.copyFile(file, exec);
                    makeExecutable(exec);
                    if (attachProgramFile) {
                        projectHelper.attachArtifact(project, programFileType, exec);
                    }
                }
            } else {
                for (File file : files) {
                    makeExecutable(file);
                }
            }

        }
        catch (IOException e) {
            throw new MojoExecutionException(e, "FAILURE!", e.getMessage());
        }

    }

    private boolean shouldProcess(Artifact artifact)
    {
        getLog().debug("Considering " + artifact);
        if (artifact == null) {
            return false;
        }

        if (!artifact.getType().equals("jar")) {
            return false;
        }

        return classifier == null || classifier.equals(artifact.getClassifier());
    }

    private void makeExecutable(File file)
            throws IOException,MojoExecutionException
    {
        getLog().debug("Making " + file.getAbsolutePath() + " executable");

        File oldJarStorage = File.createTempFile("waffles", ".tmp");
        try {
            FileUtils.rename(file, oldJarStorage);

            FileOutputStream out = null;
            FileInputStream in = null;
            InputStream scriptIn = null;
            try {
                out = new FileOutputStream(file);
                in = new FileInputStream(oldJarStorage);
                if (scriptFile == null) {
                    out.write(("#!/bin/sh\n\nexec java " + flags + " -jar \"$0\" \"$@\"\n\n").getBytes("ASCII"));
                }
                else {
                    getLog().debug(String.format("Loading file[%s] from jar[%s]", scriptFile, oldJarStorage));
                    final URLClassLoader loader = new URLClassLoader(new URL[]{oldJarStorage.toURI().toURL()}, null);
                    scriptIn = loader.getResourceAsStream(scriptFile);
                    out.write(IOUtil.toString(scriptIn).getBytes("ASCII"));
                    out.write("\n\n".getBytes("ASCII"));
                }
                IOUtil.copy(in, out);
                out.flush();
                Runtime.getRuntime().exec("chmod +x " + file.getAbsolutePath());
            }
            finally {
                IOException x = null;
                if (in != null) {
                    try {
                        in.close();
                    }
                    catch (IOException e) {
                        if (e != null) {
                            x = e;
                        }
                    }
                }
                if (out != null) {
                    try {
                        out.close();
                    }
                    catch (IOException e) {
                        if (e != null) {
                            x = e;
                        }
                    }
                }
                if (scriptIn != null) {
                    try {
                        scriptIn.close();
                    }
                    catch (IOException e) {
                        if (e != null) {
                            x = e;
                        }
                    }
                }
                if (x != null) {
                    throw x;
                }
            }
        }
        finally {
            if (!oldJarStorage.delete()) {
                throw new MojoExecutionException("FAILURE, could not delete '" + oldJarStorage.getAbsolutePath() + "'");
            }
        }
    }
}
